version: "3.9"
services:
  mopidy:
    build:
      context: ./mopidy
      dockerfile: Dockerfile
    image: "test/mopidy"
    # command: tail -f /dev/null
    # tty: true
    ports:
      - "6600:6600"
      - "6680:6680"
    devices:
      - "/dev/snd:/dev/snd"
    volumes:
      - ./fifo:/tmp/snapcast/
      - ./music:/media/music
      - ./mopidydata:/mopidy
#   redis:
#     image: "redis:alpine"
