version: "3.9"

services:
  mopidy:
    build:
      context: ./mopidy
      dockerfile: Dockerfile
      args:
        CONFIG_TARGET: server
        # server | client (default: client)
    container_name: mopidy
    image: "test/mopidy:v0.0"
    ports:
    - "6600:6600"
    - "6680:6680"
    volumes:
      # The volume with the sharesound fifo for snapcast to work
      - "./sharesound:/tmp/sharesound:ro"
      # Makes mopidy data persistent
      - "./mopidy_data:/data"
    depends_on:
      - snapserver
    restart: unless-stopped

  snapserver:
    profiles:
      - snapserver
    build:
      context: ./snapserver
      dockerfile: Dockerfile
      args:
        SNAPCAST_VERSION: 0.25.0
    container_name: snapserver
    image: test/snapserver:v0.0
    volumes:
      - "./sharesound:/tmp/sharesound:rw"
      - "./snapserver_share:/tmp/snapserver_share"
    command: "snapserver"
    # command: "snapserver -s pipe:///tmp/sharesound/snapfifo?name=MopidyPipe&codec=pcm&mode=create"
    ports:
    - "1704:1704"
    - "1705:1705"
    - "1780:1780"
    - "5000:5000"
    restart: unless-stopped

  snapclient:
    profiles:
      - snapclient
    container_name: snapclient
    image: test/snapcast:v0.0
    # Must put IP of snapserver here
    # because avahi doesnt work
    command: "snapclient --host 192.168.3.3 --user snapclient:audio"
    devices:
      # Linking to Raspberry Pi's sound card to output to
      - "/dev/snd/:/dev/snd/"
    restart: unless-stopped
